setw -g mode-keys vi

set -g status-style "bg=blue,fg=white"
set -g pane-border-style "fg=blue"

unbind p
bind p last-pane
bind-key \\ last-window
bind-key y previous-window

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
